#!/usr/bin/env bash

set -e # exit the script if any statement returns a non-true result

retrieve_genesis() {
  # Download Genesis master branch from Github
  curl -s -o /tmp/genesis-master.tar.gz -L https://github.com/lubanrb/genesis/archive/master.tar.gz
  # Untar Genesis to /tmp
  tar -xzf /tmp/genesis-master.tar.gz -C /tmp/
}

cleanup() {
  # Clean up Genesis
  rm -fr /tmp/genesis-master
  rm -fr /tmp/genesis-master.zip  
}

# Upon exit, remove tmp files
trap "cleanup" INT TERM EXIT

# Retrieve Genesis
retrieve_genesis
# Install Genesis
/tmp/genesis-master/install $@

