#!/usr/bin/env bash

set -e # exit the script if any statement returns a non-true result

# Luban Genesis is used to bootstrap the Uber application environment

print_task() {
  echo "[$(date +"%H:%M")]" $@
}

print_step() {
  echo "        "$@
}

print_line() {
  echo "        - "$@
}

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

expand_path() {
  echo $(cd $1 && pwd)
}

configure_genesis_default_options() {
  print_line "Configure Genesis default options"

  LUBAN_ROOT_PATH="/opt/luban"
  FORCE_INSTALL=false

  OPENSSL_VER="1.0.2g"
  OPENSSL_SRC_URL="http://www.openssl.org/source"

  RUBY_VER="2.3.0"
  RUBY_SRC_URL="http://ftp.ruby-lang.org/pub/ruby/${RUBY_VER%.*}"
  RDOC_OPTIONS="--no-document"
  BUNDLER_VER=""
  LUBAN_VER=""
}

configure_genesis_constom_options() {
  # Load Genesis custom options from config file if specified
  if [[ ! -z "$GENESIS_CONFIG_FILE" ]]
  then
    print_line "Configure Genesis custom options from file \"$GENESIS_CONFIG_FILE\""
    source $GENESIS_CONFIG_FILE
  fi
}

configure_genesis_system_options() {
  print_line "Configure Genesis system options"

  DEPLOY_USER="$USER"
  UBER_ENV="uber"
  UBER_STAGE="development"
  DEPLOY_ROOT=$(dirname $GENESIS_ROOT)
  UBER_ENV_ROOT="$LUBAN_ROOT_PATH/env/$UBER_STAGE.$UBER_ENV"
  LUBAN_PKG="$UBER_ENV_ROOT/.luban/pkg"
  LUBAN_TMP="$LUBAN_ROOT_PATH/tmp"
  LUBAN_DOWNLOADS="$LUBAN_ROOT_PATH/downloads"
  LUBBASE_ROOT="$UBER_ENV_ROOT/lubbase"
  LUBBASE_BIN="$LUBBASE_ROOT/bin"
  HARDWARE_NAME=$(uname -m)
  OS_NAME=$(uname -s)
  if [ "$OS_NAME" == "Darwin" ]
  then
    OSX=true
  else
    OSX=false
  fi
}

configure_genesis() {
  print_step "Configure Genesis"

  configure_genesis_default_options
  configure_genesis_constom_options
  configure_genesis_system_options
}

make_genesis_directories() {
  print_step "Make Genesis directories"

  mkdir -p $LUBAN_PKG
  mkdir -p $LUBAN_TMP
  mkdir -p $LUBAN_DOWNLOADS
  mkdir -p $LUBBASE_ROOT
  mkdir -p $LUBBASE_BIN
}

load_genesis_modules() {
  print_step "Load Genesis modules"

  source $GENESIS_ROOT/lib/install-openssl
  source $GENESIS_ROOT/lib/install-ruby
  source $GENESIS_ROOT/lib/install-gems
}

init_genesis() {
  print_task "Initialize Genesis"

  configure_genesis
  make_genesis_directories
  load_genesis_modules
}

build_genesis() {
  setup_openssl
  setup_ruby
  setup_default_gems
}

show_genesis_version() {
  GENESIS_VERSION=$(cat $GENESIS_ROOT/version)
  echo "Luban Genesis version $GENESIS_VERSION"
  echo
}

setup_genesis() {
  GENESIS_ROOT=$(expand_path $(dirname $0))
  GENESIS_CONFIG_FILE=$1
  show_genesis_version
  init_genesis 
  build_genesis
}

setup_genesis $@

