#!/usr/bin/env bash

# ==========
# YAML Setup
# ==========

setup_yaml_env_variables() {
  print_line "Setup YAML environment variables"

  YAML_HOME=$RUBY_HOME
  YAML_VER_DIR=$RUBY_VER_DIR
  YAML_VER_TMP=$RUBY_VER_TMP
  YAML_SRC_FILE=$RUBY_VER_TMP/yaml-$YAML_VER.tar.gz
  YAML_VER_INST=$RUBY_VER_TMP/yaml-$YAML_VER
  YAML_INST_LOG=$RUBY_INST_LOG
  YAML_INST_LOG_FILE=$RUBY_INST_LOG/yaml-$YAML_VER-install-$(date +%Y%m%d-%H%M).log
}

install_yaml() {
  print_line "Installing YAML"

  if [ ! -f "$YAML_SRC_FILE" ];
  then
    print_line "Downloading YAML source"
    curl -o $YAML_VER_TMP/yaml-$YAML_VER.tar.gz $YAML_SRC_URL/yaml-$YAML_VER.tar.gz >> $YAML_INST_LOG_FILE 2>&1
  fi

  print_line  "Untar'ing YAML source"
  tar -xzf $YAML_SRC_FILE -C $YAML_VER_TMP >> $YAML_INST_LOG_FILE 2>&1
  cd $YAML_VER_INST

  print_line "Configuring YAML"
  ./configure --prefix=$YAML_VER_DIR >> $YAML_INST_LOG_FILE 2>&1

  print_line "Building YAML"
  make >> $YAML_INST_LOG_FILE 2>&1

  print_line "Installing YAML"
  make install >> $YAML_INST_LOG_FILE 2>&1

  cd $DEPLOY_ROOT
}

cleanup_yaml_setup() {
  print_line "Clean up YAML setup"
  
  rm -fr $YAML_VER_INST
}

setup_yaml() {
  print_step "Setup YAML $YAML_VER"

  setup_yaml_env_variables

  if [ -e "$YAML_VER_DIR/include/yaml.h" -a -e "$YAML_VER_DIR/lib/libyaml.a" ];
  then
    if ! $FORCE_INSTALL;
    then
      cleanup_yaml_setup
      print_line "YAML $YAML_VER setup is skipped: installed ALREADY"
      return
    fi
  fi

  install_yaml
  cleanup_yaml_setup
}