#!/usr/bin/env bash

# ==================
# Default Gems Setup
# ==================

create_gems_binstubs() {
  print_line "Creating gems binstubs ..."
  for f in $RUBY_BIN/*
  do
    ln -nfs $f $LUBBASE_BIN >> $RUBY_INST_LOG_FILE 2>&1
  done
}

install_gem_bundler() {
  print_line "Install gem Bundler"

  if [[ -z "$BUNDLER_VER" ]]
  then
    $LUBBASE_BIN/gem install bundler $RDOC_OPTIONS >> $RUBY_INST_LOG_FILE 2>&1
  else
    $LUBBASE_BIN/gem install bundler --version $BUNDLER_VER $RDOC_OPTIONS >> $RUBY_INST_LOG_FILE 2>&1
  fi
}

setup_gem_bundler() {
  print_step "Setup gem Bundler $BUNDLER_VER"

  if [ -e "$RUBY_BIN/bundle" ]
  then
    if ! $FORCE_INSTALL
    then
      print_line "Bundler setup is skipped: installed ALREADY"
      return
    fi
  fi

  install_gem_bundler
}

install_gem_luban() {
  print_line "Install gem Luban"

  if [[ -z "$LUBAN_VER" ]]
  then
    $LUBBASE_BIN/gem install luban $RDOC_OPTIONS >> $RUBY_INST_LOG_FILE 2>&1
  else
    $LUBBASE_BIN/gem install luban --version $LUBAN_VER $RDOC_OPTIONS >> $RUBY_INST_LOG_FILE 2>&1
  fi
}

setup_gem_luban() {
  print_step "Setup gem Luban $LUBAN_VER"

  if [ -e "$RUBY_BIN/luban" ]
  then
    if ! $FORCE_INSTALL
    then
      print_line "Luban $LUBAN_VER setup is skipped: installed ALREADY"
      return
    fi
  fi

  install_gem_luban
}

install_default_gems() {
  setup_gem_bundler
  setup_gem_luban
  create_gems_binstubs
}

setup_default_gems() {
  print_task "Setup default gems"

  install_default_gems
}
