#!/usr/bin/env bash

# ==========
# Ruby Setup
# ==========

setup_ruby_env_variables() {
  print_step "Setup Ruby environment variables"

  RUBY_HOME=$LUBAN_PKG/ruby
  RUBY_VER_DIR=$RUBY_HOME/versions/$RUBY_VER
  RUBY_VER_TMP=$LUBAN_TMP
  RUBY_SRC_FILE=$RUBY_VER_TMP/ruby-$RUBY_VER.tar.gz
  RUBY_VER_INST=$RUBY_VER_TMP/ruby-$RUBY_VER
  RUBY_INST_LOG=$RUBY_HOME/log
  RUBY_INST_LOG_FILE=$RUBY_INST_LOG/ruby-$RUBY_VER-install-$(date +%Y%m%d-%H%M).log
}

make_ruby_directories() {
  print_step "Make Ruby directories"

  mkdir -p $RUBY_VER_DIR
  mkdir -p $RUBY_VER_TMP
  mkdir -p $RUBY_INST_LOG
}

create_ruby_symlink() {
  print_line "Creating Ruby symlinks"

  ln -nfs $RUBY_VER_DIR $RUBY_HOME/current
}

create_ruby_binstubs() {
  print_line "Create Ruby binstubs"

  for f in $RUBY_VER_DIR/bin/*
  do
    ln -fs $f $LUBAN_BIN/
  done
}

install_ruby() {
  print_step "Install Ruby $RUBY_VER"

  if [ ! -f "$RUBY_SRC_FILE" ];
  then
    print_line "Downloading Ruby source"
    curl -o $RUBY_VER_TMP/ruby-$RUBY_VER.tar.gz -L $RUBY_SRC_URL/ruby-$RUBY_VER.tar.gz >> $RUBY_INST_LOG_FILE 2>&1
  fi

  print_line  "Untar'ing Ruby source"
  tar -xzf $RUBY_SRC_FILE -C $RUBY_VER_TMP >> $RUBY_INST_LOG_FILE 2>&1
  cd $RUBY_VER_INST

  print_line "Configuring Ruby"
  ./configure --prefix=$RUBY_VER_DIR --disable-install-doc --with-opt-dir=$RUBY_VER_DIR:$OPENSSL_DIR >> $RUBY_INST_LOG_FILE 2>&1

  print_line "Building Ruby"
  make >> $RUBY_INST_LOG_FILE 2>&1

  print_line "Installing Ruby"
  make install >> $RUBY_INST_LOG_FILE 2>&1

  cd $DEPLOY_ROOT 
}

cleanup_ruby_setup() {
  print_line "Clean up Ruby setup"

  rm -fr $RUBY_VER_INST
}

post_setup_ruby() {
  cleanup_ruby_setup
  create_ruby_symlink
  create_ruby_binstubs 
}

setup_ruby() {
  print_task "Setup Ruby $RUBY_VER"

  setup_ruby_env_variables

  if [ -e "$RUBY_VER_DIR/bin/ruby" ];
  then
    if ! $FORCE_INSTALL;
    then
      print_line "Ruby $RUBY_VER setup is skipped: installed ALREADY"
      return
    fi
  fi

  make_ruby_directories
  #setup_yaml
  install_ruby
  post_setup_ruby
}
