#!/usr/bin/env bash

# ==========
# Ruby Setup
# ==========

setup_ruby_env_variables() {
  RUBY_HOME=$LUBBASE_PKGS/ruby
  RUBY_VER_DIR=$RUBY_HOME/versions/$RUBY_VER
  RUBY_VER_TMP=$RUBY_HOME/tmp
  RUBY_DOWNLOADS=$LUBAN_DOWNLOADS/ruby
  RUBY_SRC_FILE=$RUBY_DOWNLOADS/ruby-$RUBY_VER.tar.gz
  RUBY_VER_INST=$RUBY_VER_TMP/ruby-$RUBY_VER
  RUBY_INST_LOG=$RUBY_HOME/log/ruby-$RUBY_VER
  RUBY_INST_LOG_FILE=$RUBY_INST_LOG/ruby-$RUBY_VER-install-$(date +%Y%m%d-%H%M%S).log
  RUBY_BIN=$RUBY_VER_DIR/bin
}

make_ruby_directories() {
  print_step "Make Ruby directories"

  mkdir -p $RUBY_VER_DIR
  mkdir -p $RUBY_VER_TMP
  mkdir -p $RUBY_INST_LOG
  mkdir -p $RUBY_DOWNLOADS
}

create_ruby_symlink() {
  print_line "Creating Ruby symlinks"

  ln -nfs $RUBY_VER_DIR $LUBBASE_ROOT/ruby >> $RUBY_INST_LOG_FILE 2>&1
}

create_ruby_binstubs() {
  print_line "Create Ruby binstubs"

  for f in $RUBY_BIN/*
  do
    ln -nfs $f $LUBBASE_BIN >> $RUBY_INST_LOG_FILE 2>&1
  done
}

install_ruby() {
  print_step "Install Ruby $RUBY_VER"

  if [ ! -f "$RUBY_SRC_FILE" ];
  then
    print_line "Downloading Ruby source"
    curl -L -o $RUBY_SRC_FILE $RUBY_SRC_URL/ruby-$RUBY_VER.tar.gz >> $RUBY_INST_LOG_FILE 2>&1
  fi

  print_line  "Untar'ing Ruby source"
  tar -xzf $RUBY_SRC_FILE -C $RUBY_VER_TMP >> $RUBY_INST_LOG_FILE 2>&1
  cd $RUBY_VER_INST

  print_line "Configuring Ruby"
  ./configure --prefix=$RUBY_VER_DIR --disable-install-doc --enable-shared --without-tcl --without-tk --with-opt-dir=$OPENSSL_VER_DIR >> $RUBY_INST_LOG_FILE 2>&1

  print_line "Building Ruby"
  make >> $RUBY_INST_LOG_FILE 2>&1

  print_line "Installing Ruby"
  make install >> $RUBY_INST_LOG_FILE 2>&1

  # Remove static Ruby library to save disk space
  rm -f $RUBY_VER_DIR/lib/libruby-static.a

  cd $DEPLOY_ROOT 
}

cleanup_ruby_setup() {
  print_line "Clean up Ruby setup"

  rm -fr $RUBY_VER_INST
}

post_setup_ruby() {
  cleanup_ruby_setup
  create_ruby_symlink
  create_ruby_binstubs 
}

setup_ruby() {
  print_task "Setup Ruby $RUBY_VER"

  setup_ruby_env_variables

  if [ -e "$RUBY_BIN/ruby" ]
  then
    if ! $FORCE_INSTALL
    then
      print_line "Ruby $RUBY_VER setup is skipped: installed ALREADY"
      return
    fi
  fi
  
  make_ruby_directories
  install_ruby
  post_setup_ruby
}
